# Default values for mynats2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nats:
  nats:
    image: nats:2.9.7-alpine
    pullPolicy: IfNotPresent

    jetstream:
      enabled: true
  cluster:
    enabled: true
    replicas: 3

    # disable cluster advertisements when running behind a load balancer
    noAdvertise: true