apiVersion: v1
kind: Service
metadata:
  name: {{ include "mynats2.fullname" . }}-lb
  labels:
    {{- include "mynats2.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: nats
  ports:
    - name: nats
      port: 4222
      protocol: TCP
      targetPort: 4222
    - name: monitor
      port: 8222
      protocol: TCP
      targetPort: 8222
    - name: metrics
      port: 7777
      protocol: TCP
      targetPort: 7777